### PR TITLE
add style to header on desktop

### PR DESCRIPTION
**Pull request by maknetaRo**

### CODE REVIEW

**Review by yanpelov — COMMENTED** [review]
1. what does data-menu-toggle in label mean? Needed?
2. I think we could save space if we could leave out the "Email Address" and "Total Emails". I would consider just writing "mail@domain.com (12,444)"
3. i liked the minimalistic theme of the total emails and email address more than the yellow button. what if we could use a refresh icon (⟳) instead of a yellow button? 
4. in the max-sm media query, maybe we could consider not using the hamburger and a pop up window, but rather keeping the email address and the total emails, and use a refresh icon and a signout icon.  It could simplify the code a little.

**Comment by maknetaRo** [comment]
> 1. what does data-menu-toggle in label mean? Needed? - _if we resign from hamburger menu all this would be useless but it seems I started doing it in another way and then rewrote_
> 2. I think we could save space if we could leave out the "Email Address" and "Total Emails". I would consider just writing "[mail@domain.com](mailto:mail@domain.com) (12,444)" - _if you think so_ 
> 3. i liked the minimalistic theme of the total emails and email address more than the yellow button. what if we could use a refresh icon (⟳) instead of a yellow button? - _no problem - black on white without any borders, only icon?_ 
> 4. in the max-sm media query, maybe we could consider not using the hamburger and a pop up window, but rather keeping the email address and the total emails, and use a refresh icon and a signout icon. It could simplify the code a little. - _what is your proposition for signout icon, as we haven't decided on the layout of our app I wouldn't like to do some useless work again_

**Comment by yanpelov** [comment]
How about that? That's just an idea. Do you like it? If not, we can stay with the current. It's totally fine.

Slide1

Slide2

**Comment by maknetaRo** [comment]
> How about that? That's just an idea. Do you like it? If not, we can stay with the current. It's totally fine.
> 
Looks cool!

**Comment by yanpelov** [comment]
Code looks good. Design wise I would just maybe consider:
1. having the Gmail cleaner logo, the profile text (email address+count), refresh icon, signin/out icons align vertically on the same baseline
2. have all elements on the same proptionate size and weight - e.g. the text is smaller and thinner than the icons. I would suggest either thinnig the icons or thickening the text. Gmail cleaner logo is bigger than the other icons, I would suggest making it a little smaller.
3. I would consider putting the refresh icon on the left side (beside the sign in/out icon).

You can use the helper lines for assistance. 

Screen Shot 2020-09-20 at 16 06 16

**Comment by yanpelov** [comment]
i think that the profile text could be a little bigger and line spacing between email address an total count could be smaller, but other that its totally fine.

**Comment by yanpelov** [comment]
Please merge

**Comment by maknetaRo** [comment]
Should I merge into master also? I've just merged into development.

pon., 21 wrz 2020 o 09:46 yanpelov <notifications@github.com> napisał(a):

**Pull request merged**
