### PR TITLE
#8  header bar  sign out

### PR DESCRIPTION
**Pull request by afeezdev**
I'm still working on how to display the username

### CODE REVIEW

**Review by maknetaRo — APPROVED** [review]
Looks good.

**Comment by yanpelov** [comment]
1. when you merged the development branch, you have removed the file loader part and thus the image loading doesn't work and the inbox picture isn't displayed.

2. the number of messages is displayed instead of the number of threads.

**Review by yanpelov — COMMENTED** [review]
I would suggest using Sign In and Sign Out instead of all uppercase, so it would be more coherent to the other texts

**Review by yanpelov — COMMENTED** [review]
another.js file should be deleted

**Review by yanpelov — COMMENTED** [review]
please remove comments in code about username
gmailConnector.js:21
index.html:17

**Comment by yanpelov** [comment]
All seems good, except I meant deleting the comments about username, as we don't have one, not uncommenting them.
Other than that, I think it's good to merge

**Comment by yanpelov** [comment]
Hi Afeez,
1. You made changes in the last commit, but it's not what I meant..

My suggestion was to keep the gmailConnector as an only API Interface.

AKA, you use it's interface to grab the information you need and with the data you get, you handle it, outside of this interface.

In the change, you took out the whole function of the getProfile outside of the gmailConnector.

The function should stay there, along with the code that does the API request to grab the profile information.

Now, I suggest, creating your own separate js file, where you call this getProfile function, and then you use the data however you want, but *outside* the interface.

The interface should only handle connection with Gmail to gather data or send data.
But how we handle the data or modify it, should be outside of this interface.

You see what I mean?

Actually, now that I am thinking about it, me too, have to do these improvements as well, and take all data information manipulation (like duplication removal), outside of the gmailConnector.

2. Another suggestion, is to show the 'Email Address' and the 'Total Emails: Number of Threads' texts, only after the user is signed in, not before.

**Comment by afeezdev** [comment]
> Hi Afeez,
> 1.
> You made changes in the last commit, but it's not quite what I meant..
> 
> My suggestion was to keep the gmailConnector as an only API Interface.
> 
> AKA, it should be used as an interface to grab the information from Gmail. You get the data from the interface and you handle it, outside of this interface.
> 
> In the change, you took out the whole function of the getProfile outside of the gmailConnector.
> 
> The function should stay in gmailConnector, along with the code that does the API request to grab the profile information.
> 
> I suggest, creating your own separate js file, where you call this getProfile function, and then you use the data however you want, but _outside_ the interface.
> 
> The interface should only handle the connection with Gmail to gather data or send data.
> But how we handle the data or modify it, should be outside of this interface.
> 
> Do you see what I mean?
> 
> Actually, now that I am thinking about it, me too, have to do these improvements as well, and take all data information manipulation (like duplication removal), outside of the gmailConnector.
> 2.
> Another suggestion is to show the 'Email Address' and the 'Total Emails: Number of Threads' texts, only after the user is signed in, not before.

Before I made  recent changes,  I think  only grab the information needed from getEmailProfile.
I move it out of the gmail connector js because I thought that's what you meant.
Perhaps you can throw more light because I'm kind of confused

**Comment by yanpelov** [comment]
> > Hi Afeez,
> > 1.
> > You made changes in the last commit, but it's not quite what I meant..
> > My suggestion was to keep the gmailConnector as an only API Interface.
> > AKA, it should be used as an interface to grab the information from Gmail. You get the data from the interface and you handle it, outside of this interface.
> > In the change, you took out the whole function of the getProfile outside of the gmailConnector.
> > The function should stay in gmailConnector, along with the code that does the API request to grab the profile information.
> > I suggest, creating your own separate js file, where you call this getProfile function, and then you use the data however you want, but _outside_ the interface.
> > The interface should only handle the connection with Gmail to gather data or send data.
> > But how we handle the data or modify it, should be outside of this interface.
> > Do you see what I mean?
> > Actually, now that I am thinking about it, me too, have to do these improvements as well, and take all data information manipulation (like duplication removal), outside of the gmailConnector.
> > 2.
> > Another suggestion is to show the 'Email Address' and the 'Total Emails: Number of Threads' texts, only after the user is signed in, not before.
> 
> Before I made recent changes, I think only grab the information needed from getEmailProfile.
> I move it out of the gmail connector js because I thought that's what you meant.
> Perhaps you can throw more light because I'm kind of confused

can you contact me on discord?

**Comment by afeezdev** [comment]
> > > Hi Afeez,
> > > 1.
> > > You made changes in the last commit, but it's not quite what I meant..
> > > My suggestion was to keep the gmailConnector as an only API Interface.
> > > AKA, it should be used as an interface to grab the information from Gmail. You get the data from the interface and you handle it, outside of this interface.
> > > In the change, you took out the whole function of the getProfile outside of the gmailConnector.
> > > The function should stay in gmailConnector, along with the code that does the API request to grab the profile information.
> > > I suggest, creating your own separate js file, where you call this getProfile function, and then you use the data however you want, but _outside_ the interface.
> > > The interface should only handle the connection with Gmail to gather data or send data.
> > > But how we handle the data or modify it, should be outside of this interface.
> > > Do you see what I mean?
> > > Actually, now that I am thinking about it, me too, have to do these improvements as well, and take all data information manipulation (like duplication removal), outside of the gmailConnector.
> > > 2.
> > > Another suggestion is to show the 'Email Address' and the 'Total Emails: Number of Threads' texts, only after the user is signed in, not before.
> > 
> > 
> > Before I made recent changes, I think only grab the information needed from getEmailProfile.
> > I move it out of the gmail connector js because I thought that's what you meant.
> > Perhaps you can throw more light because I'm kind of confused
> 
> can you contact me on discord?

ok, i will do that

**Comment by yanpelov** [comment]
to make life a little simple: i mean something like this:

1. in src/js/gmailConnector.js, return this function to this file:
function getEmailProfile() {	
  gapi.client.gmail.users.getProfile({	
    'userId': 'me'	
  }).then(function (response) {	
    return response.result; 	
  });	
}	

2.inside src/js/getEmailProfile.js (I would change name to headerDispaly.js to something):
make a new function called displayUserProfile (or something similar):
inside displayUserProfile call getEmailProfile,something like this:
let{emailAddress, threadsTotal } = getEmailProfile();
      userEmail.innerText = emailAddress;
      totalEmails.innerText = threadsTotal;

That is what I meant between separating the interface (gmailConnector.js) and your code (inside displayUserProfile).

**Pull request merged**
